version: '3'
services:
  web:
    image: leon/composeapp
    command: python app.py
    ports:
     - "5000:5000"
    volumes:
     - .:/composeapp
  redis:
    image: registry.docker-cn.com/library/redis
